### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by GbengaOdesanmi** [ycz0512/Soft-Q-learning-for-Space-Robot#1]
Hi, please am trying to run this code and am having this error,  but latter got it fixed but I cant get the code running

python experiment/controller.py

Connected to remote V-REP server.
_________________________ Start Episode 1 _________________________
set target velocity error 3
Traceback (most recent call last):
  File "experiment/controller.py", line 67, in <module>
    next_obs, reward, terminal, env_info = env.step(*action)        # *action, shape[3]
  File "/home/gbenga/Downloads/Soft-Q-learning-for-Space-Robot-master/experiment/softqlearning/environment/space_robot_3link.py", line 219, in step
    self._set_joint_effort(action)
  File "/home/gbenga/Downloads/Soft-Q-learning-for-Space-Robot-master/experiment/softqlearning/environment/space_robot_3link.py", line 159, in _set_joint_effort
    raise Exception('failed to set target velocity to joints.')
Exception: failed to set target velocity to joints.

python experiment/controller.py

Connected to remote V-REP server.
_________________________ Start Episode 1 _________________________

**Comment by ycz0512** [comment]
Sorry to reply lately at this point, for my neglect of close attention to this repo.
This error shows up when the target velocities of joints are not successfully set (i.e. the function 'simxSetJointTargetVelocity' is not executed fine somehow). It's a simulator problem. When that happens, I manually throw such an error like this.

            _ = vrep.simxSetJointTargetVelocity(self.clientID, self.handles['joint'][i],
                                                self.joint_target_velocities[i],
                                                vrep.simx_opmode_blocking)
            # Just in case
            if _ != 0:
                print('set target velocity error %s' % _)
                raise Exception('failed to set target velocity to joints.')

Restarting the whole training procedure will slove this issue.  
Make sure that the V-REP simulator is already launched when you run the 'main' code: experiment.space_3link_sql.py

For more details, refer to 'simxSetJointTargetVelocity' in the link below:
[http://www.coppeliarobotics.com/helpFiles/en/remoteApiFunctionsPython.htm](url)
